version: "3.9"

services:
  app:
    build:
      context: .
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_PUBLISHABLE_KEY: ${VITE_SUPABASE_PUBLISHABLE_KEY}
        VITE_GEMINI_API_KEY: ${VITE_GEMINI_API_KEY}
        VITE_ELASTICSEARCH_URL: ${VITE_ELASTICSEARCH_URL:-http://elasticsearch:9200}
        VITE_ELASTICSEARCH_USERNAME: ${VITE_ELASTICSEARCH_USERNAME}
        VITE_ELASTICSEARCH_PASSWORD: ${VITE_ELASTICSEARCH_PASSWORD}
    image: lex-ai-advisor:latest
    container_name: lex-ai-app
    ports:
      - "8080:80"
    environment:
      # runtime envs are not read by Vite client code, but can be used by Nginx or future server-side features
      - NODE_ENV=production
    depends_on:
      - elasticsearch
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: lex-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: lex-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped

volumes:
  es_data:


