version: '3.8'

services:
  # Elasticsearch service with resource limits
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: lex-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx512m"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - lex-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Proxy server for document downloads
  proxy-server:
    build: .
    container_name: lex-proxy-server
    environment:
      - NODE_ENV=production
    depends_on:
      - elasticsearch
    networks:
      - lex-network
    command: ["node", "server-proxy.js"]
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Main application
  app:
    build: .
    container_name: lex-ai-advisor
    environment:
      - NODE_ENV=production
    depends_on:
      - elasticsearch
      - proxy-server
    ports:
      - "8080:8080"
    networks:
      - lex-network
    command: ["npm", "run", "preview"]
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  elasticsearch_data:

networks:
  lex-network:
    driver: bridge
